# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 02:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, choices=[('man', '男'), ('woman', '女')], default='man', max_length=55, null=True, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=22, null=True, verbose_name='手机号')),
                ('age', models.CharField(blank=True, max_length=9, null=True, verbose_name='年龄')),
                ('head', models.ImageField(default='static/User/head/default.jpg', upload_to='static/User/head', verbose_name='默认头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
