# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '收藏课程',
                'verbose_name_plural': '收藏课程',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='collection_num',
            field=models.IntegerField(default=0, verbose_name='收藏数量'),
        ),
        migrations.AddField(
            model_name='collection',
            name='course',
            field=models.ManyToManyField(to='course.Course', verbose_name='关联课程'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='课程作者'),
        ),
    ]
