# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190510_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='course',
        ),
        migrations.AddField(
            model_name='collection',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='关联课程'),
        ),
    ]
